### ISSUE TITLE
`playerVolumeEntityId` doesn't  have any effect

### ISSUE THREAD

**Issue by nomike** [punxaphil/maxi-media-player#124]
**Checklist:**

- [X ] I updated to the latest version available
- [X ] I cleared the cache of my browser

**Release with the issue:**
v1.14.2

**Last working release (if known):**
Not known, it's the first time, I'm using this card.

**Browser and Operating System:**

Various (Firerox, Chrome. Windows 11, Ubuntu 24.04)

**Description of problem:**

I have an Onkyo A/V receiver with a Chromecast with Google TV attached to it.
As the Chromecast doesn't support volume control, I need to control the volume of the Onkyo.
I still need to control the other media functions on the Chromecast.

I tried setting the `playerVolumeEntityId` parameter, but volume control in the dashboard doesn't work and I'm getting an the error that the chromecast doesn't support volume comntrol. So it looks like that parameter doesn't have an effect.

So either there is a bug, I'm using it wrong or I don't understand what `playerVolumeEntityId` is supposed to do.

**Additional information:**

This is the config I'm using:

```yaml
type: custom:maxi-media-player
sections:
  - player
entities:
  - media_player.living_room_tv_2_2
showVolumeUpAndDownButtons: false
showFastForwardAndRewindButtons: false
hidePlayerControlPowerButton: true
topFavorites:
  - ""
dynamicVolumeSlider: false
hideBrowseMediaButton: false
hideVolumeCogwheel: false
playerVolumeEntityId: media_player.onkyo_tx_nr646
```
