### ISSUE TITLE
Problem with favourites

### ISSUE THREAD

**Issue by PrzemekSkw** [punxaphil/maxi-media-player#142]
**Checklist:**

- [X] I updated to the latest version available
- [X] I cleared the cache of my browser

Hello, I'm looking for help how to add Favourites. By default I get all radio browser countries. 
![image](https://github.com/user-attachments/assets/53c2463b-81b6-4902-b94a-a5994c841543)

1. How to hide them?
I try something like that:
```
type: custom:maxi-media-player
sections:
  - player
  - volumes
  - groups
  - grouping
  - media browser
  - queue
startSection: player
entities:
  - media_player.hub
  - media_player.glosniki
  - media_player.emilki
showAudioInputFormat: false
showVolumeUpAndDownButtons: false
favoritesItemsPerRow: 4
customFavorites:
  all:
    - title: Old Christmas
      media_content_id: spotify:track:6oLfnEF4sqpPHGHDhe8YWK
      media_content_type: music
      thumbnail: >-
        https://ew.com/thmb/6j3FoouU-wDY6jEwjVC3AVowrBQ=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/Christmas-Album-Frank-Sinatra-d4cfdfdafb0945679b38240485ff8bda.jpg
```
I add my favourite playlists from spotify and it shows but also shows me radio stations from radio browser as favourites. The worst tihing is that they don't work  when I click some country.

![image](https://github.com/user-attachments/assets/a9cbf55e-b0b4-4ea0-ba7d-113a833c884e)

I have to click Browse media to play radio stations. How to reemove that stations from favourites?

Regards.
