### ISSUE TITLE
Can't Play Spotify or SiriusXM to Alexa Devices - There IS a Solution!!

### ISSUE THREAD

**Issue by ColtonYYZ** [punxaphil/maxi-media-player#146]
So people over at Alexa Media Player (AMP) have blocked sending the content ID "music" (and something else I forget) essentially restricting those who are wanting to use their online streaming service through any media player in Hass.

There are solutions!! I would like to explain with hopes that Maxi Media Player *could* ultimately be the only one that allows integration of all services. It's really not a difficult thing to do - at least, it doesn't appear to be. Please let me discuss this with you! My handle over at Discord is the same here as it is there.

**Checklist:**

- [ ] I updated to the latest version available
- [ ] I cleared the cache of my browser

**Release with the issue:**

**Last working release (if known):**

**Browser and Operating System:**

**Description of problem:**

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by punxaphil** [comment]
Please share here, I am not using Discord really.

**Comment by ColtonYYZ** [comment]
Do you have another method of communication you would prefer? It's more of a quick discussion rather than typing out everything, only to find out it wouldn't work with your integration. Like I use a script and tell Alexa to ask MyMediaAlexa to play my local music. The 2 online streaming services I use, Spotify and SiriuxXM both have Alexa skills, so I can start listening to my music by telling her or I have buttons I tap on that run a script to tell her to play online music to my Alexa speakers. On the frontend, it's as if we are using the media player, but in reality on the backend it's using the skills for the appropriate service. The media player still shows the artwork etc.

**Comment by punxaphil** [comment]
Alright, so you want the card to call your script?

**Comment by DJ-CrossFade** [comment]
> So people over at Alexa Media Player (AMP) have blocked sending the content ID "music" (and something else I forget) essentially restricting those who are wanting to use their online streaming service through any media player in Hass.
> There are solutions!! I would like to explain with hopes that Maxi Media Player _could_ ultimately be the only one that allows integration of all services. It's really not a difficult thing to do - at least, it doesn't appear to be. Please let me discuss this with you! My handle over at Discord is the same here as it is there.
> 
> **Checklist:**
> 
> * [ ]  I updated to the latest version available
> * [ ]  I cleared the cache of my browser
> 
> **Release with the issue:**
> 
> **Last working release (if known):**
> 
> **Browser and Operating System:**
> 
> **Description of problem:**
> 
> **Javascript errors shown in the web inspector (if applicable):**
> 
> ```
> 
> ```
> 
> **Additional information:**

This was a major drag for me too. This player's appearance looks amazing and so does its zone controls and other functionality. But 5 of the 7 speakers in my house are Alexas. I was bummed when I had to uninstall this player due to all the hiccups communicating with the speakers. I'm mainly chiming in so I'll get notifications if a solution is found. Awesome job on the player though. It seems fantastic for compatible hardware.

**Comment by ColtonYYZ** [comment]
> Alright, so you want the card to call your script?

Sorry, I didn't see your reply until now.  Yeah! I mean, it's not pretty but gets the job done. Maybe in the UI there can be an entry box for those with Alexa devices, the ability to enter in a script they've created that tells SiriusXM or Spotify (and likely every other player that has a Alexa Skill) to play their music.

Here's the script I use:
```
alias: play siriusxm 90s9
sequence:
  - data:
      media_content_id: play 90s on 9 on SiriusXM
      media_content_type: custom
    action: media_player.play_media
    target:
      entity_id: media_player.my_echo_show
description: ""
```
The media_content_id: is the same thing as verbally saying outloud, "Alexa, play 90s on 9 on SiriusXM" So with this field, I am attaching an excel file (if you need me to convert it to something more useable, I can) of all the stations currently offered. I have placed a red box around the column that the integration would use. At least I believe that is the case. The spreadsheet also includes the description of the channel and I can retrieve all the logos for them if you think that would be a nice touch too.

I'm thinking if the UI could have a section for Alexa Users, where they could select the online provider (Ex SiriusXM) and then from there, they can select the channel they want to listen to, or they can type in the channel number if they know it.

On the backend, the script simply retrieves the speaker they chose to play their music, and retrieves their selection of channel in the drop down menu, and plus them into the scipt and fires it off to Alexa. The artwork pulls through for both SiriusXM and Spotify when the media_player field is read, so that might have to be adjusted for Alexa users also, but that's easy to do also.

A side note, spotify also can be done via a script but it's a little bit more work because of the user's playlists, but is possible.

Here's my script for Spotify, using SpotCast integration:
```
            - name: My Playlist
              type: service
              id: spotcast.start
              data:
                device_name: My Echo Show
                uri: spotify:playlist:7Tm9rYzQaG87huJK5LEK3v    #<--------  Users need to obtain this from Spotify. It's explained in the SpotCast Integration
                random_song: true
                shuffle: true
```
If you're open to this idea and would like help with anything that I may be able to do, I'm certainly happy to be of service. I don't want all the onus on you, so whatever I can do for you, simply let me know!  My email is the same name here at gmail so feel free to shoot me an email!

[Sirius-Channel-Guide.xlsx](https://github.com/user-attachments/files/18295195/Sirius-Channel-Guide.xlsx)
