### ISSUE TITLE
FR add option to list entity: media_player.abc

### ISSUE THREAD

**Issue by Mariusthvdb** [punxaphil/maxi-media-player#52]
**Checklist:**

- [ ] I updated to the latest version available
- [ ] I cleared the cache of my browser

**Release with the issue:**

**Last working release (if known):**

**Browser and Operating System:**

**Description of problem:**

No supported players found

trying to use your card in auto-entities, 
```
    - type: custom:auto-entities
      card:
        type: custom:maxi-media-player
      filter:
        include:
          - domain: media_player
      # card_param: entities # is default, so not required
```

we get the below error, because your card does not accept

```
    - type: custom:maxi-media-player
      entities:
        - entity: media_player.googlehome_library
        - entity: media_player.googlehome_hal
 ```
which what auto-entities produces, (and probably all HA card using entities accept).

So, please consider accepting that in the config of your card, do we can create an auto-generated card config 

**Javascript errors shown in the web inspector (if applicable):**

<img width="1247" alt="Scherm­afbeelding 2024-06-20 om 11 37 40" src="https://github.com/punxaphil/maxi-media-player/assets/33354141/e3b95ac5-01ec-424c-9b82-ef4ca367b131">

**Additional information:**
https://community.home-assistant.io/t/maxi-media-player/705007/16?u=mariusthvdb

https://community.home-assistant.io/t/auto-entities-automatically-fill-cards-with-entities/147801/1359?u=mariusthvdb

**Comment by Mariusthvdb** [comment]
![image](https://github.com/punxaphil/maxi-media-player/assets/33354141/23a1ccae-a97d-4105-910f-83f20611fc3a)

**Comment by punxaphil** [comment]
Where do you see in the docs that the format should be `entity: ....`?
This page https://www.home-assistant.io/dashboards/entity-filter/ indicates that list of entity ids is ok, which is what maxi-media-player supports
![image](https://github.com/punxaphil/maxi-media-player/assets/26582898/1000a5e3-f8e4-448a-b733-f81473dadec5)

**Comment by Mariusthvdb** [comment]
I,m not saying it should be, I am saying it accepts it, sorry if that came across the wrong way

**Comment by punxaphil** [comment]
I still don't understand how it would help. Nothing in the link below says it should be in that format. Unless I am missing something?
https://github.com/thomasloven/lovelace-auto-entities

**Comment by Mariusthvdb** [comment]
yes, your card can not accept

```
    - type: custom:maxi-media-player
      entities:
        - entity: media_player.googlehome_library
        - entity: media_player.googlehome_hal
   ```

but only entities like

``
    - type: custom:maxi-media-player
      entities:
        - media_player.googlehome_library
        - media_player.googlehome_hal
  ```

however, most other card accept the `entity:` so you can set names and other options. Most importantly in this FR though is the reason auto-entities outputs the list with the `entity: ` as Ive posted above.
